/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-08-28 03:13:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1472347284868L));
    _jspx_dependants.put("/include/navbar.jsp", Long.valueOf(1472350908517L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<!--  Bootstrap meta tags  -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <!--  Other heads -->\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>DBL - About</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!--  Page styling -->\r\n");
      out.write("    <link href=\"css/general.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/navbar.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!--  Navbar -->\r\n");
      out.write("\t\t");
      out.write("<!--  This file contains the information of the navigation bar -->\r\n");
      out.write("<!-- Navbar content -->\r\n");
      out.write("<div class=\"navbar-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-static-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"active\">\r\n");
      out.write("\t\t\t\t<form action='control' method='POST'>\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name=\"action\" value=\"viewIndexPage\"/>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-link\">\r\n");
      out.write("\t\t\t\t\t\tHome\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\t\t\t\t<form action='control' method='POST'>\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name=\"action\" value=\"viewAboutPage\"/>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-link\">\r\n");
      out.write("\t\t\t\t\t\tAbout\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("          \t<li>\r\n");
      out.write("\t\t\t\t<form action='control' method='POST'>\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name=\"action\" value=\"viewCartPage\"/>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-link\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-shopping-cart\"></span>\r\n");
      out.write("\t\t\t\t\t\tView Cart (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userBean.cart.numItems}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("          \t</li>\r\n");
      out.write("          </ul>          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Page Content -->\r\n");
      out.write("\t\t<h1>About</h1>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tThis web application is designed for an assignment in the COMP9321 course at UNSW.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t");
      out.write("<!-- Footer content -->\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<footer class=\"container-fluid\">\r\n");
      out.write("\t<center><p>&copy; 2016</p></center>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
